### ISSUE TITLE
/lib/libc.so.6: version `GLIBC_2.33' not found (required by ./bbpPairings.exe)

### ISSUE THREAD

**Issue by C1977** [BieremaBoyzProgramming/bbpPairings#18]
Can someone help please?

 ./bbpPairings.exe
./bbpPairings.exe: /lib/libc.so.6: version `GLIBC_2.33' not found (required by ./bbpPairings.exe)
./bbpPairings.exe: /lib/libc.so.6: version `GLIBC_2.25' not found (required by ./bbpPairings.exe)
./bbpPairings.exe: /lib/libc.so.6: version `GLIBC_2.35' not found (required by ./bbpPairings.exe)
./bbpPairings.exe: /lib/libc.so.6: version `GLIBC_2.32' not found (required by ./bbpPairings.exe)
./bbpPairings.exe: /lib/libc.so.6: version `GLIBC_2.34' not found (required by ./bbpPairings.exe)
./bbpPairings.exe: /lib/libc.so.6: version `GLIBC_2.36' not found (required by ./bbpPairings.exe)
skgronau.de>

skgronau.de> uname -a
Linux gwaay 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_6                              4 x86_64 x86_64 GNU/Linux

**Comment by jbierema** [comment]
@C1977 Apparently the system you&rsquo;re running on has an old version of glibc. The simplest solutions would be to update the system or to compile BBP Pairings on that system if possible. Since the error message says glibc 2.25 was not found, and that was released in 2017, it seems possible that the latter would not work either, since the source code uses C++20. We may need to try to figure out where the program is making use of these newer versions of glibc and look for a way to avoid doing so. Unfortunately, I do not have the capacity to investigate that.

I am very much a novice when it comes to issues like this, so this answer is to the best of my current understanding.

**Comment by C1977** [comment]
I got this working finally with a new hosting company and I created a REST API to access bbpPairings. Do you allow to open this for everyone (it is free and will be free forever)?
![2023-12-28 01_47_01-Mozilla Firefox](https://github.com/BieremaBoyzProgramming/bbpPairings/assets/36223435/ad265bbc-7f9d-4da8-937e-134fcce0e972)

**Comment by C1977** [comment]
changed provider who directly offered to update glibc to 2.36 after the same error occured, then it was solved.
