### ISSUE TITLE
Sorting score groups in Burstein

### ISSUE THREAD

**Issue by jbfsoftware** [BieremaBoyzProgramming/bbpPairings#2]
Hello Jeremy,

I am currently verifying your Burstein engine with the internal one of Sevilla. I run into differences caused by different sorting of score groups (and the floaters). From your documentation I understand that BBP Pairings sorts  on Sonneborn-Berger, Buchholz score, Buchholz tiebreak, Median score, Median tiebreak. You calculate the "score" as "tiebreak multiplied with score". Sevilla sorts on Sonneborn-Berger, Buchholz tiebreak and Median tiebreak only. In the FIDE documentation (C4.3.4, point 3.2) "basic pairing principles" this is mentioned too. Of course this results into pairing diffferences from time to time, especially when there are floaters.

Did I miss anything in the (FIDE) documentation, is this a bug in the BBP Pairings engine, maybe a deliberate change, maybe a future Burstein version? 

Best regards, JP.

**Comment by jbfsoftware** [comment]
Example: In the included file BBP Pairings paired in round 3 101-105 98-67. Sevilla paired 98-105 101-67.
Player 105 has Bhlz 2.0, Score 1.5 thus multiplied 3.
Player 67 has Bhlz 2,5 Score 1.0 thus multiplied 2.5.
Therefore Sevilla sorts the 2.5 before 2 (67 first) and BBP Pairings sorts 3 before 2.5 (105 first).

[test.zip](https://github.com/BieremaBoyzProgramming/bbpPairings/files/1082709/test.zip)

**Comment by jbierema** [comment]
Hello, JP.

First, thank you for pointing this out. We do sometimes misunderstand the rules (as our version history shows), so we always appreciate questions about whether we have made a mistake.

In my understanding, the "Buchholz tiebreak" as we call it is intended for breaking ties between players with the same raw score. When there is a floater, the case you pointed out, we are comparing people with different raw scores, so we should compare them using the "Buchholz score," not the Buchholz tiebreak. People with the same raw score should be compared using the Buchholz tiebreak. (The Buchholz score works equally well here except in the case that the player's score is zero.)

Again, this is my understanding, and I cannot cite any official document to say that this is the correct interpretation. But I did ask Mr. Burstein this question, and he confirmed that we need to factor in the player's own raw score in the case of a floater with a different raw score.

If you find additional discrepancies, whether due to bugs or interpretation questions, I am interested in hearing about them.

**Comment by jbfsoftware** [comment]
Hi Jeremy,
Thanks for your quick answer. It is clear. No doubt Mr Burstein is the first resource to know this. Too bad only it's not that clear in the specs on the FIDE site. However, I'll add the score weighted criteria in Sevilla and will resume testing. If oddities happen I will keep you informed.
Thanks for your support.
JP
